# Makefile wrapper to keep output Dockerfiles from being cleaned up.

.PRECIOUS: pkg/pillar/Dockerfile
.PRECIOUS: pkg/qrexec-dom0/Dockerfile
.PRECIOUS: pkg/qrexec-lib/Dockerfile
.PRECIOUS: pkg/xen-tools/Dockerfile

include Makefile
